export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const REGISTRAR_PRODUCTO = 'REGISTRAR_PRODUCTO';
export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO';
export const MODIFICAR_PRODUCTO = 'MODIFICAR_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';